---
Name: featuredimageconfig
Only:
  moduleexists: 'silverstripe/cms'
---

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - DFT\SilverStripe\FeaturedImage\ObjectExtension

---
Only:
  moduleexists: 'silverstripe/blog'
---

SilverStripe\Blog\Model\BlogPost:
  extensions:
    - DFT\SilverStripe\FeaturedImage\BlogPostExtension